#!/usr/bin/env bash
# Regression checks for the Copier update workflow's safety guards.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKFLOW="${ROOT_DIR}/.github/workflows/copier-update.yml"

python3 - "${WORKFLOW}" <<'PY'
from pathlib import Path
import sys

workflow = Path(sys.argv[1]).read_text()
stage = workflow.index("git add --all")
no_op = workflow.index("git diff --cached --quiet")
assert stage < no_op, "untracked-file staging must precede the no-op check"
assert "isDraft" in workflow and "isPrerelease" in workflow
assert "publishedAt" in workflow
assert "Ref must identify a published, non-draft, non-prerelease release" in workflow
PY

validate_release() {
  local ref="$1" release="$2"
  jq -e --arg ref "${ref}" \
    '(.tagName == $ref) and (.isDraft == false) and (.isPrerelease == false) and (.publishedAt != null and .publishedAt != "")' \
    <<<"${release}" >/dev/null
}

validate_release v2.21.5 '{"tagName":"v2.21.5","isDraft":false,"isPrerelease":false,"publishedAt":"2026-09-19T00:00:00Z"}'
if validate_release v9.9.9 '{"tagName":"v9.9.9","isDraft":false,"isPrerelease":false,"publishedAt":null}'; then
  echo "FAIL: unreleased SemVer-shaped tag was accepted" >&2
  exit 1
fi

fixture="$(mktemp -d)"
trap 'rm -rf "${fixture}"' EXIT
mkdir "${fixture}/repo"
cd "${fixture}/repo"
git init -q
git config user.name fixture
git config user.email fixture@example.invalid
printf 'base\n' > tracked.txt
git add tracked.txt
git commit -qm initial

# This is the Copier-only-new-file regression: staging must make the update
# non-empty, so the workflow takes its commit/push path rather than no-op.
printf 'generated by Copier\n' > generated.txt
git add --all
if git diff --cached --quiet; then
  echo "FAIL: Copier-created untracked file was treated as a no-op" >&2
  exit 1
fi

echo "PASS: Copier update workflow safety guards"
