#!/usr/bin/env bash
# Regression checks for the Copier update workflow's safety guards.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKFLOW="${ROOT_DIR}/.github/workflows/copier-update.yml"
UPDATE_SCRIPT="${ROOT_DIR}/scripts/dev/copier-update.sh"

python3 - "${WORKFLOW}" "${UPDATE_SCRIPT}" <<'PY'
from pathlib import Path
import sys

workflow = Path(sys.argv[1]).read_text()
script = Path(sys.argv[2]).read_text()
assert "scripts/dev/copier-update.sh" in workflow
stage = script.index("git add --all")
no_op = script.index("git diff --cached --quiet")
assert stage < no_op, "untracked-file staging must precede the no-op check"
assert "gh release view" in script
assert "isDraft" in script and "isPrerelease" in script
assert "publishedAt" in script
assert "Ref must identify a published, non-draft, non-prerelease release" in script
PY

fixture="$(mktemp -d)"
trap 'rm -rf "${fixture}"' EXIT
mkdir -p "${fixture}/bin" "${fixture}/repo" "${fixture}/remote.git"

cat >"${fixture}/bin/gh" <<'MOCK_GH'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${GH_CALL_LOG}"
if [[ "${GH_MODE:-}" == "unreleased" ]]; then
  printf '{"tagName":"v9.9.9","isDraft":false,"isPrerelease":false,"publishedAt":null}\n'
else
  printf '{"tagName":"v2.21.5","isDraft":false,"isPrerelease":false,"publishedAt":"2026-09-19T00:00:00Z"}\n'
fi
MOCK_GH
cat >"${fixture}/bin/copier" <<'MOCK_COPIER'
#!/usr/bin/env bash
set -euo pipefail
printf 'generated by Copier\n' > generated.txt
MOCK_COPIER
chmod +x "${fixture}/bin/gh" "${fixture}/bin/copier"

# Exercise the production release API guard with a mocked gh response. This is
# a SemVer-shaped tag that is not a published release and must be rejected.
export PATH="${fixture}/bin:${PATH}"
export GH_CALL_LOG="${fixture}/gh-calls.log"
export TEMPLATE_REF=v9.9.9 GH_MODE=unreleased BRANCH=automation/test GITHUB_STEP_SUMMARY="${fixture}/summary"
if (cd "${fixture}/repo" && "${UPDATE_SCRIPT}"); then
  echo "FAIL: production release guard accepted an unreleased tag" >&2
  exit 1
fi
grep -F -- 'release view v9.9.9 --repo quokkify/project-toolkit --json tagName,isDraft,isPrerelease,publishedAt' "${GH_CALL_LOG}" >/dev/null

# Run the production commit/push path against a local bare remote. Copier only
# creates an untracked file; the script must stage, commit, and push it.
git init -q --bare "${fixture}/remote.git"
git init -q "${fixture}/repo"
git -C "${fixture}/repo" config user.name fixture
git -C "${fixture}/repo" config user.email fixture@example.invalid
printf 'base\n' > "${fixture}/repo/tracked.txt"
git -C "${fixture}/repo" add tracked.txt
git -C "${fixture}/repo" commit -qm initial
git -C "${fixture}/repo" remote add origin "${fixture}/remote.git"
export TEMPLATE_REF=v2.21.5 GH_MODE=published BRANCH=automation/test GITHUB_STEP_SUMMARY="${fixture}/summary"
export GITHUB_SERVER_URL=https://github.com GITHUB_REPOSITORY=fixture/repo DEFAULT_BRANCH=main
(cd "${fixture}/repo" && "${UPDATE_SCRIPT}")
git --git-dir="${fixture}/remote.git" show "refs/heads/automation/test:generated.txt" | grep -Fx 'generated by Copier' >/dev/null
git -C "${fixture}/repo" log -1 --format=%s | grep -Fx 'chore(template): update shared project template' >/dev/null

echo "PASS: Copier update workflow release guard and commit/push path"
